import { markAssetError } from 'next/dist/client/route-loader'
import { Inter } from 'next/font/google'
//import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const style1={margin:0,padding:0};
  return (
    <html lang="en">
      <body className={inter.className} style={style1}>{children}</body>
    </html>
  )
}
